# This workflow will install Python dependencies and run tests

name: Run os tests on Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - name: Install xvfb for headless testing for ubuntu-latest
      run: sudo apt-get install xvfb
      if: matrix.os == 'ubuntu-latest' 

    - name: Checkout 
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v3
        
    - name: Test with unittest for ubuntu-latest
      run: |
        # Automatic test discover runs all test*.py modules inside the test package
        xvfb-run python -m unittest
      if: matrix.os == 'ubuntu-latest'

    - name: Test with unittest for windows-latest and macos-latest
      run: |
       # Automatic test discover runs all test*.py modules inside the test package
       python -m unittest
      if: matrix.os != 'ubuntu-latest'



